<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Nilai extends Model
{
    use HasFactory;

    protected $fillable = [
        'siswa_id',
        'agama_tugas1',
        'agama_tugas2',
        'agama_tugas3',
        'agama_tugas4',
        'agama_tugas5',
        'agama_uts',
        'agama_uas',
        'pancasila_tugas1',
        'pancasila_tugas2',
        'pancasila_tugas3',
        'pancasila_tugas4',
        'pancasila_tugas5',
        'pancasila_uts',
        'pancasila_uas',
        'indonesia_tugas1',
        'indonesia_tugas2',
        'indonesia_tugas3',
        'indonesia_tugas4',
        'indonesia_tugas5',
        'indonesia_uts',
        'indonesia_uas',
        'matematika_tugas1',
        'matematika_tugas2',
        'matematika_tugas3',
        'matematika_tugas4',
        'matematika_tugas5',
        'matematika_uts',
        'matematika_uas',
        'pjok_tugas1',
        'pjok_tugas2',
        'pjok_tugas3',
        'pjok_tugas4',
        'pjok_tugas5',
        'pjok_uts',
        'pjok_uas',
        'sbk_tugas1',
        'sbk_tugas2',
        'sbk_tugas3',
        'sbk_tugas4',
        'sbk_tugas5',
        'sbk_uts',
        'sbk_uas',
        'inggris_tugas1',
        'inggris_tugas2',
        'inggris_tugas3',
        'inggris_tugas4',
        'inggris_tugas5',
        'inggris_uts',
        'inggris_uas',
        'muatanlokal_tugas1',
        'muatanlokal_tugas2',
        'muatanlokal_tugas3',
        'muatanlokal_tugas4',
        'muatanlokal_tugas5',
        'muatanlokal_uts',
        'muatanlokal_uas',
    ];

    protected $casts = [
        'agama_tugas1' => 'decimal:2',
        'agama_tugas2' => 'decimal:2',
        'agama_tugas3' => 'decimal:2',
        'agama_tugas4' => 'decimal:2',
        'agama_tugas5' => 'decimal:2',
        'agama_uts' => 'decimal:2',
        'agama_uas' => 'decimal:2',
        'pancasila_tugas1' => 'decimal:2',
        'pancasila_tugas2' => 'decimal:2',
        'pancasila_tugas3' => 'decimal:2',
        'pancasila_tugas4' => 'decimal:2',
        'pancasila_tugas5' => 'decimal:2',
        'pancasila_uts' => 'decimal:2',
        'pancasila_uas' => 'decimal:2',
        'indonesia_tugas1' => 'decimal:2',
        'indonesia_tugas2' => 'decimal:2',
        'indonesia_tugas3' => 'decimal:2',
        'indonesia_tugas4' => 'decimal:2',
        'indonesia_tugas5' => 'decimal:2',
        'indonesia_uts' => 'decimal:2',
        'indonesia_uas' => 'decimal:2',
        'matematika_tugas1' => 'decimal:2',
        'matematika_tugas2' => 'decimal:2',
        'matematika_tugas3' => 'decimal:2',
        'matematika_tugas4' => 'decimal:2',
        'matematika_tugas5' => 'decimal:2',
        'matematika_uts' => 'decimal:2',
        'matematika_uas' => 'decimal:2',
        'pjok_tugas1' => 'decimal:2',
        'pjok_tugas2' => 'decimal:2',
        'pjok_tugas3' => 'decimal:2',
        'pjok_tugas4' => 'decimal:2',
        'pjok_tugas5' => 'decimal:2',
        'pjok_uts' => 'decimal:2',
        'pjok_uas' => 'decimal:2',
        'sbk_tugas1' => 'decimal:2',
        'sbk_tugas2' => 'decimal:2',
        'sbk_tugas3' => 'decimal:2',
        'sbk_tugas4' => 'decimal:2',
        'sbk_tugas5' => 'decimal:2',
        'sbk_uts' => 'decimal:2',
        'sbk_uas' => 'decimal:2',
        'inggris_tugas1' => 'decimal:2',
        'inggris_tugas2' => 'decimal:2',
        'inggris_tugas3' => 'decimal:2',
        'inggris_tugas4' => 'decimal:2',
        'inggris_tugas5' => 'decimal:2',
        'inggris_uts' => 'decimal:2',
        'inggris_uas' => 'decimal:2',
        'muatanlokal_tugas1' => 'decimal:2',
        'muatanlokal_tugas2' => 'decimal:2',
        'muatanlokal_tugas3' => 'decimal:2',
        'muatanlokal_tugas4' => 'decimal:2',
        'muatanlokal_tugas5' => 'decimal:2',
        'muatanlokal_uts' => 'decimal:2',
        'muatanlokal_uas' => 'decimal:2',
    ];
}
